### ISSUE TITLE
[Other] Android Release on F-Droid

### ISSUE THREAD

**Issue by JonnyHaystack** [CometTools/LunaSea#205]
Hi, thanks for the great app.

Might you consider getting it added to the [F-Droid](https://f-droid.org/) repos? Seeing as it's an open-source app and some of us would rather not have to use the Play Store :stuck_out_tongue:

**Comment by JagandeepBrar** [comment]
I’ll take a look soon! They have complex deployment guidelines so I’ll have to ensure that LunaSea adheres to them.

**Comment by JagandeepBrar** [comment]
Because of the recent implementation of IAP donations, sadly this is no longer possible :(

F-Droid requires that the application does not rely on Google Play Services in anyway, and now it does. At some point I can make another build flavour, but I haven't investigated it at all so maybe someone who has more knowledge on build flavours can help me out with this.

There are APKs available in the GitHub releases page though! The app internally checks for IAP-capability, so it would just be disabled for a manual installed release.

**Comment by JonnyHaystack** [comment]
Ah no worries, would be cool to see it on there in the future though if you're able to figure that out :smile:

**Comment by Wonderfall** [comment]
+1, looking forward to see this awesome app on F-Droid! But I'm already glad I found it.
Is there another way to make a one-time donation? My phone has no Google Services (I installed the app with Aurora Droid) so I can't go the IAP way.

**Comment by JagandeepBrar** [comment]
@Wonderfall I have a Ko-Fi page setup here: https://ko-fi.com/jagandeepbrar

Thanks! :)

**Comment by JagandeepBrar** [comment]
Closing the issue as this will never be possible with the current architecture of LunaSea sadly, as it will always require Google Play Services.
