### ISSUE TITLE
Play protect warning - google play store

### ISSUE THREAD

**Issue by johnmoxon** [CometTools/LunaSea#438]
Hi There

Just a note to say when I updated the app this morning from the Google Play Store I got a warning saying that LunaSea had been blocked by GooglePlay protect and may be harmful.  Hope its an error.

Cheers

**Comment by JagandeepBrar** [comment]
Hi @johnmoxon,

Thanks for the heads up on this. I imagine it is because of the following two warnings that are issue inside of my Google Play Console:

<img width="1019" alt="Screen Shot 2021-04-20 at 5 49 30 PM" src="https://user-images.githubusercontent.com/3048295/115473166-d4462a80-a200-11eb-857f-0f732aff3825.png">

<img width="1027" alt="Screen Shot 2021-04-20 at 5 51 12 PM" src="https://user-images.githubusercontent.com/3048295/115473255-02c40580-a201-11eb-8a04-5287b46047a4.png">

For the first one: It is a legacy permission that I have forgotten to remove since LunaSea moved to exporting files (logs, backups, etc.) to the sharesheet. This will be removed in the next build available, and before the public release of v5.0.0 (in the coming days).

As for the second one: This has already been fixed since an early v5.0.0, but since v5.0.0 has not hit the public release yet it is possible it is also causing a warning.

**Comment by JagandeepBrar** [comment]
Can you confirm this is still showing a warning? I have just installed the Play Store release and see a "Verified by Play Protect" with a green shield on the Play Store.

![Screenshot_20210420-181446](https://user-images.githubusercontent.com/3048295/115475121-93e8ab80-a204-11eb-870e-24c664ffc64c.png)

**Comment by JagandeepBrar** [comment]
Hey @johnmoxon, as I haven't heard anything back and after verifying with a few other users, I don't believe this is an issue anymore.

If it is, please reopen the issue.

**Comment by johnmoxon** [comment]
Apologies @JagandeepBrar, I have been away.  Yes! it looks like you have resolved the issue and is now showing as verified by play protect in the google play store
