### ISSUE TITLE
[Other] Add Kofi/Github Sponsors Link inside the app

### ISSUE THREAD

**Issue by sadstan123456** [CometTools/LunaSea#473]
Title,

**Comment by JagandeepBrar** [comment]
This isn't possible because of both Google and Apple not allowing you to redirect any customers to another form of payment (even if that payment is not actually purchasing content for the app).

I already tried and LunaSea got rejected on both stores, so I removed the links. I do hope this changes in the future one day.

**Comment by sadstan123456** [comment]
That is unfortunate. Perhaps a link to the app's Github page then?

**Comment by JagandeepBrar** [comment]
> That is unfortunate. Perhaps a link to the app's Github page then? That would be to show the app's source code

It's already linked within the app! You can find many links (including to the GitHub) in Settings -> Resources.
